- name: NVM - Install NVM
  become: true
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | sudo -E bash -

- name: NVM - Define NVM_DIR in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NVM - Define nvm.sh in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NODEJS - Install NVM
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: source /home/{{ansible_env.SUDO_USER}}/.zshrc && nvm install v18

- name: NPM - Check if local global path installed
  become_user: "{{ansible_env.SUDO_USER}}"
  stat:
    path: /home/{{ansible_env.SUDO_USER}}/.npm-packages
    register: npm_local_packages

- name: NPM - Local global packages directory
  become_user: "{{ansible_env.SUDO_USER}}"
  when: not npm_local_packages.stat.exists
  shell: mkdir "/home/{{ansible_env.SUDO_USER}}/.npm-packages"

- name: NPM - Set global packages directory
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: npm config set prefix "/home/{{ansible_env.SUDO_USER}}/.npm-packages"

- name: NPM - Define NPM_PACKAGE in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: NPM_PACKAGES="${HOME}/.npm-packages"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NPM - Add NPM_PACKAGE to .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export PATH="$PATH:$NPM_PACKAGES/bin"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NPM - Add NPM MANPATH to .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
    owner: "{{ansible_env.SUDO_USER}}"