- name: OH-MY-ZSH - Check if installed
  become: yes
  become_user: "{{ansible_env.SUDO_USER}}"
  stat:
    path: /home/{{ansible_env.SUDO_USER}}/.oh-my-zsh
  register: ohmyzsh

- name: OH-MY-ZSH - Download  installer
  become: yes
  become_user: "{{ansible_env.SUDO_USER}}"
  when: not ohmyzsh.stat.exists
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{ansible_env.SUDO_USER}}/oh-my-zsh-installer.sh

- name: OH-MY-ZSH - Run installer
  become: yes
  become_user: "{{ansible_env.SUDO_USER}}"
  when: not ohmyzsh.stat.exists
  shell: /usr/bin/bash /home/{{ansible_env.SUDO_USER}}/oh-my-zsh-installer.sh
  environment:
    CHSH: no
    RUNZSH: no

- name: OH-MY-ZSH - Remove the installer
  become: yes
  become_user: "{{ansible_env.SUDO_USER}}"
  when: not ohmyzsh.stat.exists
  file: path=/home/{{ansible_env.SUDO_USER}}/oh-my-zsh-installer.sh state=absent

- name: OH-MY-ZSH Change theme to agnoster
  become: yes
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: /usr/bin/sed -i 's/"robbyrussell"/"agnoster"/g' ~/.zshrc