- name: NVM - Install NVM
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash

- name: NVM - Define NVM_DIR in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export NVM_DIR="$HOME/.nvm"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NVM - Define load NVM in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    owner: "{{ansible_env.SUDO_USER}}"

- name: NVM - Define BASH COMPLETION in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    owner: "{{ansible_env.SUDO_USER}}"

- name: NPM - Check if local global path installed
  become_user: "{{ansible_env.SUDO_USER}}"
  stat:
    path: /home/{{ansible_env.SUDO_USER}}/.npm-packages
  register: npm_local_packages

- name: NPM - Local global packages directory
  become_user: "{{ansible_env.SUDO_USER}}"
  when: not npm_local_packages.stat.exists
  shell: mkdir "/home/{{ansible_env.SUDO_USER}}/.npm-packages"

- name: NPM - Set global packages directory
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: npm config set prefix "/home/{{ansible_env.SUDO_USER}}/.npm-packages"

- name: NPM - Define NPM_PACKAGE in .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: NPM_PACKAGES="${HOME}/.npm-packages"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NPM - Add NPM_PACKAGE to .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export PATH="$PATH:$NPM_PACKAGES/bin"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NPM - Add NPM MANPATH to .zshrc
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    dest: "/home/{{ansible_env.SUDO_USER}}/.zshrc"
    line: export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
    owner: "{{ansible_env.SUDO_USER}}"

- name: NPM - Define ~/.npmrc file
  become_user: "{{ansible_env.SUDO_USER}}"
  lineinfile:
    create: true
    present: true
    dest: "/home/{{ansible_env.SUDO_USER}}/.npmrc"
    line: 'prefix=~/.npm-packages'
    owner: "{{ansible_env.SUDO_USER}}"

- name: NODEJS - Install Node 18 using NVM
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: /bin/bash -c "source /home/{{ansible_env.SUDO_USER}}/.zshrc && nvm install --lts --no-progress --latest-npm"

- name: NODEJS - Install YARN using npm
  become_user: "{{ansible_env.SUDO_USER}}"
  shell: /bin/bash -c "source /home/{{ansible_env.SUDO_USER}}/.zshrc && npm install -g yarn"