- name: PHP - Add Ondrej PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: PHP - Install PHP 8.1 CLI
  apt:
    state: latest
    pkg:
    - openssl
    - php8.1-cli
    - php8.1-curl
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-xml
    - php8.1-zip
    - php8.1-xdebug
    - php8.1-soap
    - php8.1-redis
    - php8.1-pgsql
    - php8.1-mongodb
    - php8.1-mcrypt
    - php8.1-ldap
    - php8.1-imagick
    - php8.1-gd
    - php-json

- name: PHP - Download Composer
  script: scripts/download_composer.sh

- name: PHP - Install composer Globally
  become: true
  command: mv composer.phar /usr/local/bin/composer

- name: PHP - Set permissions on Composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"

- name: PHP - Download phpMD.phar
  ansible.builtin.command:
    cmd: wget -O /home/{{ansible_env.SUDO_USER}}/phpmd.phar -c https://phpmd.org/static/latest/phpmd.phar
    creates: /home/{{ansible_env.SUDO_USER}}/phpmd.phar

- name: PHP - Set persmissions on phpMD.phar
  become: true
  file:
    path: /home/{{ansible_env.SUDO_USER}}/phpmd.phar
    mode: "a+x"