- name: PHP - Add Ondrej PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: PHP - Install PHP 8.2 CLI
  apt:
    state: latest
    pkg:
    - openssl
    - php8.2-cli
    - php8.2-curl
    - php8.2-mbstring
    - php8.2-mysql
    - php8.2-xml
    - php8.2-zip
    - php8.2-xdebug
    - php8.2-soap
    - php8.2-redis
    - php8.2-pgsql
    - php8.2-mongodb
    - php8.2-mcrypt
    - php8.2-ldap
    - php8.2-imagick
    - php8.2-gd
    - php-json

- name: PHP - Download Composer
  script: scripts/download_composer.sh

- name: PHP - Install composer Globally
  become: true
  command: mv composer.phar /usr/local/bin/composer

- name: PHP - Set permissions on Composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"

- name: PHP - Download phpMD.phar
  ansible.builtin.command:
    cmd: wget -O /home/{{ansible_env.SUDO_USER}}/phpmd.phar -c https://phpmd.org/static/latest/phpmd.phar
    creates: /home/{{ansible_env.SUDO_USER}}/phpmd.phar

- name: PHP - Set persmissions on phpMD.phar
  become: true
  file:
    path: /home/{{ansible_env.SUDO_USER}}/phpmd.phar
    mode: "a+x"